--2.1. Một sinh viên chỉ được tham gia một đề tài. 

CREATE OR ALTER TRIGGER CHECK_SV_DT
ON SV_DETAI
AFTER INSERT, UPDATE
AS
BEGIN
    DECLARE @MSSV CHAR(8)
    SET @MSSV = (SELECT MSSV
    FROM inserted)

    IF (SELECT COUNT(MSDT)
    FROM SV_DETAI
    WHERE @MSSV = SV_DETAI.MSSV) > 1
    BEGIN
        RAISERROR ('A student can only participate in one project.', 16, 1)
        ROLLBACK TRANSACTION
        RETURN
    END
END

INSERT INTO SV_DETAI
VALUES('13520001', '97005')
--2.2. Điểm của đề tài trong thang điểm từ 0 đến 10.
ALTER TABLE GV_HDDT ADD CONSTRAINT CHECK_GRADE_HDDT CHECK(DIEM >= 0 AND DIEM < 10)
ALTER TABLE GV_PBDT ADD CONSTRAINT CHECK_GRADE_PBDT CHECK(DIEM >= 0 AND DIEM < 10)
ALTER TABLE GV_UVDT ADD CONSTRAINT CHECK_GRADE_UVDT CHECK(DIEM >= 0 AND DIEM < 10)

UPDATE GV_HDDT SET DIEM = 11 WHERE MSDT = '97002'
--2.3. GV là chủ tịch hội đồng phải có học vị tiến sĩ.
GO
CREATE OR ALTER TRIGGER CHECK_HV_CTHD ON HOIDONG
AFTER INSERT, UPDATE 
AS BEGIN
    IF NOT EXISTS(SELECT MSHD
    FROM INSERTED I, HOCVI HV , GV_HV_CN GHC
    WHERE I.MSGV = GHC.MSGV AND HV.MSHV = GHC.MSHV AND HV.TENHV = N'Tiến sĩ')
    begin
        PRINT N'CHỦ TỊCH HỘI ĐỒNG PHẢI LÀ TIẾN SĨ'
        ROLLBACK TRANSACTION
    END
END

SELECT *
FROM HOIDONG
SELECT *
FROM GV_HV_CN
UPDATE HOIDONG SET MSGV =203 WHERE MSHD = 1
---2.4. Tính số lượng đề tài làm phản biện và số lượng đề tài làm ủy viên của từng GV.
CREATE TABLE GV_DTPB_DTUV
(
    MSGV INT NOT NULL,
    PBDT INT ,
    UVDT INT ,
    FOREIGN KEY (MSGV) REFERENCES  GIAOVIEN(MSGV)
)
GO
CREATE OR ALTER PROC GV_DTPB_DTUV_CUR
AS
BEGIN
    DECLARE @DUYET CURSOR, @MSGV char(6), @PBDT INT, @UVDT INT
    SET @DUYET = CURSOR FOR SELECT MSGV
    FROM GIAOVIEN
    OPEN @DUYET
    FETCH NEXT FROM @DUYET INTO @MSGV
    WHILE @@FETCH_STATUS = 0
BEGIN
        --logic 
        SELECT @PBDT = COUNT(MSDT)
        FROM GV_PBDT
        WHERE @MSGV = GV_PBDT.MSGV
        SELECT @UVDT = COUNT(MSDT)
        FROM GV_UVDT
        WHERE @MSGV = GV_UVDT.MSGV
        --INSERT
        INSERT INTO GV_DTPB_DTUV
        VALUES(@MSGV, @PBDT, @UVDT)
        FETCH NEXT FROM @DUYET INTO @MSGV
    END
    CLOSE @DUYET
END

EXEC GV_DTPB_DTUV_CUR
SELECT * FROM GV_DTPB_DTUV

---In ra danh sách tên các sinh viên có điểm trung bình đề tài cao nhất.

CREATE TABLE DETAI_DIEM1
(
    MSDT CHAR(6) NOT NULL,
    DIEMTB FLOAT NOT NULL
)
GO
CREATE PROC DTB_CUR1
AS
BEGIN
    DECLARE @DUYET CURSOR, @msdt char(6), @dtb float
    SET @DUYET = CURSOR FOR SELECT MSDT
    FROM DETAI
    OPEN @DUYET
    FETCH NEXT FROM @DUYET INTO @msdt
    WHILE @@FETCH_STATUS = 0
BEGIN
        --logic 
        SELECT @dtb = AVG(DIEM)
        FROM (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            SELECT *
                FROM GV_HDDT
            UNION
                SELECT *
                FROM GV_PBDT
            UNION
                SELECT *
                FROM GV_UVDT) AS BANGTONGHOP
        WHERE BANGTONGHOP.MSDT = @msdt
        INSERT INTO DETAI_DIEM1
        VALUES(@msdt, @dtb)
        FETCH NEXT FROM @DUYET INTO @msdt
    END
    CLOSE @DUYET
END

GO
--THUC THI
EXEC DTB_CUR1


--IN RA DS HS CO DIEM TRUNG BINH CAO NHAT
GO
CREATE OR ALTER PROC HIGHEST_AVG
AS
BEGIN
    DECLARE @MAX_DIEM FLOAT
    SET @MAX_DIEM = (SELECT MAX(DIEMTB) FROM DETAI_DIEM1)
    
    SELECT SV.MSSV, DIEM.DIEMTB
    FROM DETAI_DIEM1 DIEM, SV_DETAI SV  
    WHERE DIEM.DIEMTB = @MAX_DIEM AND DIEM.MSDT = SV.MSDT
END

EXEC HIGHEST_AVG

--3.1. Tạo ra 3 users: GIANGVIEN, GIAOVU và SINHVIEN, đặt mật khẩu tuỳ ý.
CREATE LOGIN GIANGVIEN WITH PASSWORD = 'Matkhau_giangvien1';
CREATE LOGIN GIAOVU WITH PASSWORD = 'Matkhau_giaovu1';
CREATE LOGIN SINHVIEN WITH PASSWORD = 'Matkhau_sinhvien1';

CREATE USER GIANGVIEN FOR LOGIN GIANGVIEN;
CREATE USER GIAOVU FOR LOGIN GIAOVU;
CREATE USER SINHVIEN FOR LOGIN SINHVIEN;

-- Cấp quyền SELECT và UPDATE trên tất cả các bảng trong database
GRANT SELECT, UPDATE ON DATABASE::QUANLYDETAI TO GIAOVU;

-- Cấp quyền SELECT trên các bảng liên quan đến thông tin GV, đề tài, hội đồng
GRANT SELECT,UPDATE ON GIAOVIEN TO GIANGVIEN;
GRANT SELECT ON HOCVI TO GIANGVIEN;
GRANT UPDATE ON HOCHAM TO GIANGVIEN;
GRANT SELECT ON CHUYENNGANH TO GIANGVIEN;
GRANT SELECT ON GV_HV_CN TO GIANGVIEN;
GRANT SELECT ON DETAI TO GIANGVIEN;
GRANT SELECT ON GV_UVDT TO GIANGVIEN;
GRANT SELECT ON GV_PBDT TO GIANGVIEN;
GRANT SELECT ON GV_HDDT TO GIANGVIEN;
GRANT SELECT ON HOIDONG_GV TO GIANGVIEN;
GRANT SELECT ON HOIDONG TO GIANGVIEN;


GRANT SELECT ON SINHVIEN TO SINHVIEN
GRANT SELECT ON DETAI TO SINHVIEN
GRANT SELECT ON SV_DETAI TO SINHVIEN
GRANT SELECT ON HOIDONG TO SINHVIEN 
GRANT SELECT ON HOIDONG_GV TO SINHVIEN 
GRANT SELECT ON HOIDONG_DT TO SINHVIEN


-- TẤT CẢ NGƯỜI DÙNG KHÔNG CÓ QUYỀN DELETE
DENY DELETE ON DATABASE::QUANLYDETAI TO GIAOVU;
DENY DELETE ON DATABASE::QUANLYDETAI  TO GIANGVIEN;
DENY DELETE ON DATABASE::QUANLYDETAI  TO SINHVIEN;
